### ISSUE TITLE
Missing Include File

### ISSUE THREAD

**Issue by elael** [rock-core/tools-pocolog2msgpack#4]
Just updated and tried to compile. The 'msgpack.h' header seems to be missing.

>   tools/pocolog2msgpack: In file included from /home/elael/dev/squid/tools/pocolog2msgpack/src/Converter.cpp:1:0:
>   tools/pocolog2msgpack: /home/elael/dev/squid/tools/pocolog2msgpack/src/Converter.hpp:2:10: fatal error: msgpack.h: No such file or directory
>   tools/pocolog2msgpack: #include <msgpack.h>
>   tools/pocolog2msgpack: ^~~~~~~~~~~
>   tools/pocolog2msgpack: In file included from /home/elael/dev/squid/tools/pocolog2msgpack/src/pocolog2msgpack.cpp:1:0:
>   tools/pocolog2msgpack: /home/elael/dev/squid/tools/pocolog2msgpack/src/Converter.hpp:2:10: fatal error: msgpack.h: No such file or directory
>   tools/pocolog2msgpack: #include <msgpack.h>
>   tools/pocolog2msgpack: ^~~~~~~~~~~
>   tools/pocolog2msgpack: compilation terminated.
>   tools/pocolog2msgpack: compilation terminated.
>   tools/pocolog2msgpack: CMakeFiles/pocolog2msgpack.dir/build.make:62: recipe for target 'CMakeFiles/pocolog2msgpack.dir/src/pocolog2msgpack.o' failed
>   tools/pocolog2msgpack: make[2]: *** [CMakeFiles/pocolog2msgpack.dir/src/pocolog2msgpack.o] Error 1
>   tools/pocolog2msgpack: make[2]: *** Waiting for unfinished jobs....
>   tools/pocolog2msgpack: CMakeFiles/pocolog2msgpack.dir/build.make:86: recipe for target 'CMakeFiles/pocolog2msgpack.dir/src/Converter.o' failed
>   tools/pocolog2msgpack: make[2]: *** [CMakeFiles/pocolog2msgpack.dir/src/Converter.o] Error 1
>   tools/pocolog2msgpack: CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pocolog2msgpack.dir/all' failed
>   tools/pocolog2msgpack: make[1]: *** [CMakeFiles/pocolog2msgpack.dir/all] Error 2
>   tools/pocolog2msgpack: Makefile:129: recipe for target 'all' failed
>   tools/pocolog2msgpack: make: *** [all] Error 2

**Comment by AlexanderFabisch** [comment]
Hi @elael ,

it comes from the dependency `tools/msgpack-c`. It has been added recently to rock-core's `package_set`. It should be installed to `$AUTOPROJ_CURRENT_ROOT/include/msgpack.h`. I forgot to include this explicitely in the CMakeLists.txt of pocolog2msgpack. In my case it works because the other dependencies of pocolog2msgpack have the same include folder. This is probably not the case on your machine(?) Anyway, this is a bug and I assume it should be fixed with the latest commit on master. Could you try?

**Comment by elael** [comment]
Hi @AlexanderFabisch ,
I do have `tools/msgpack-c` on my rock-core, but I do have it on `$AUTOPROJ_CURRENT_ROOT/tools/msgpack-c/include`. It has no impact in what I'm doing right now, I'll try to include it on the CMakeList.

**Comment by elael** [comment]
compiling perfectly now.
