### ISSUE TITLE
depends on python-msgpack which is unavailable on Ubuntu 20.04

### ISSUE THREAD

**Issue by doudou** [rock-core/tools-pocolog2msgpack#5]
Focal dropped the python 2 package python-msgpack. Can we upgrade this to python3 ? Could we do it on 18.04 as well ?

**Comment by AlexanderFabisch** [comment]
Hi, I don't exactly know how to do that. Python 3 is definitely supported though.

**Comment by AlexanderFabisch** [comment]
is it just

```
  <depend package="tools/msgpack-c" />
  <depend package="python3" optional="1" />
  <depend package="python3-nose" optional="1" />
  <depend package="python3-pexpect" optional="1" />
  <depend package="python3-msgpack" optional="1" />
```

?

**Comment by doudou** [comment]
In principle, yes. Not sure what are the implications for the rest of the Python stuff in Rock. @2maz ?

**Comment by 2maz** [comment]
I cannot see any major implications resulting from this change and if @AlexanderFabisch gives his approval then we are good to go.

**Comment by AlexanderFabisch** [comment]
The only other thing that we have to change is the CI. Didn't @planthaber prepare default docker containers that can be used to test rock packages? Can we use it here? Does it work with CircleCI?

**Comment by AlexanderFabisch** [comment]
OK, I updated the docker image for CI and the dependencies. One problem that I had is that the package `python3-distutils` is now required to install the Python library but it is not defined in any package set (I guess). Can we add it?

**Comment by doudou** [comment]
Ping @2maz, you're much more up-to-date on the Python stuff it seems

**Comment by 2maz** [comment]
I do not see a problem of adding the osdeps: rock-core/package_set#175

**Comment by AlexanderFabisch** [comment]
OK, I'll uncomment the line in the manifest when this is merged.

**Comment by 2maz** [comment]
@AlexanderFabisch just merged

**Comment by AlexanderFabisch** [comment]
Thanks, this issue should be solved then.
